### ISSUE TITLE
[bugs] cant open other apps from an immortalized app

### ISSUE THREAD

**Issue by Hamzabdx** [sergealagon/Immortalizer#1]
[bug] cant open other apps from an immortalized app then it suddenly opens once i leave tHe immortalized app also i had another bug where the keyboard would not show in sileo which i have it immortalized im on ios 16.2 iphone 14 pm dopamine 2 latest version

**Comment by sergealagon** [comment]
Can you tell me step by step on how to replicate the bug you’re experiencing?

For the second bug you mentioned, I tried immortalizing Sileo and the keyboard works just as fine for me. 

Try disabling all your tweaks (except Immortalizer and its dependencies) to see if the issue is still there. If the issue disappears, tell me the list of your tweaks. I will check if they might have a conflict with Immortalizer.

**Comment by Hamzabdx** [comment]
The second bug isnt happening anymore the first one try immortalizing settings app then go to your tweaks preferences and try opening any of the links you have on the bottom they wont open in safari until you leave the settings app

**Comment by Hamzabdx** [comment]
I just figured out how to reproduce the second bug immortalize both settings app and sileo open settings app while sileo isnt in app switcher the open keyboard in settings app the without closing keyboard go back to homescreen the open sileo and try to open keyboard it will stay empty

**Comment by Hamzabdx** [comment]
It might be conflicting with some other tweak i have bcz i can reproduce now easily in sileo and whatsapp only in search bar the keyboard shows in conversations but not in the search bar i will try to find out what it it tomorrow

**Comment by sergealagon** [comment]
I tried replicating exactly like what you've describe, but I can't seem to trigger the bug you're experiencing. Immortalizing settings app and going to my tweak prefs to open one of the links works just as expected.

Even the second bug doesn't trigger for me. Leaving the keyboard on immortalized settings then opening sileo and opening keyboard works fine. It minimized the keyboard from settings when I use keyboard on sileo. And vice versa.

If you believe it might be conflicting with a tweak, try disabling all of them except Immortalizer, then enable your tweaks one by one, until you find the tweak affects it. Then let me know what tweak it is so I can make necessary fixes.

**Comment by sergealagon** [comment]
I've tried immortalizing 10 apps all running at the same time. No issues on my end. I'm on 16.1.1 dopamine. Though I've released version 1.0.1 here that adds additional safety checks, maybe that will solve your problem. Try it and let me know

**Comment by Hamzabdx** [comment]
I just updated to this version and the not  opening other apps while immortalized bug is fixed even when every other tweak is enabled but the keyboard bug is still there even when all other tweaks are disabled heres my tweaklist from sileo
[Tweaklist.txt](https://github.com/user-attachments/files/17667561/Tweaklist.txt)

**Comment by Hamzabdx** [comment]
Heres a video of it

https://github.com/user-attachments/assets/ff0a6f73-98fd-4884-aad6-25a8021cacaf

**Comment by Hamzabdx** [comment]
Btw there another bug which existed for me in backgrounder thats why i didnt mention it which is when you go to setting for example open keyboard leave it the switch to twitter for example there will be a ghost keyboard which hides ui as if the keyboard is open in twitter but it isnt open

**Comment by sergealagon** [comment]
Good thing it has fixed the major bug for you. 

However, I can’t still replicate that keyboard bug

https://github.com/user-attachments/assets/5795c1d0-5f24-4051-b1c8-edf1b50deb3c

It doesn’t happen to me. Maybe there’s a tweak that has changed in your files that makes the bug persist even if you have disabled all tweaks already.

**Comment by Hamzabdx** [comment]
No i disnt have this bug in backgrounder i had the ghost keyboard bug but not this i started getting this after installing immortilizer but maybe youre right

**Comment by Hamzabdx** [comment]
Also when i disable this tweak in the app the bug disappears

**Comment by sergealagon** [comment]
Oh I meant the ghost keyboard bug with backgrounder. What I'm trying to say is basically the bug you're experiencing on immortalizer and on backgrounder have something in common. It stops the keyboard view (or the its UI) from showing correctly. I had backgrounder as well before even making this tweak and I never experience ghost keyboard bug on that tweak either. I'm curious what's the culprit. It may be one of your installed tweaks.

**Comment by Hamzabdx** [comment]
Ok ill try to figure it out can you not make a fix for it to not happen? since you have an idea on what is happening thanks in advance

**Comment by sergealagon** [comment]
I may have an idea what's happening, but I won't be able to pinpoint the exact cause since I have no idea what tweak is causing the conflict. I'm trying some of your installed tweaks to see if I can replicate the bug. I won't be able to fix it if I can't replicate the bug. Let me see what I can do.

**Comment by Hamzabdx** [comment]
Ok thanks bro

**Comment by Hamzabdx** [comment]
Never mind i just uninstalled and then installed the latest version again and the bug is completely gone i think the bug was in ver 1 and persisted

**Comment by sergealagon** [comment]
That's good to know! Could be the old version was still cached, since dopamine's respring works a bit different. Hopefully by now it works continuously without any problems.

**Comment by Hamzabdx** [comment]
Lol the bug immidiatly came back thats why i deleted that

**Comment by sergealagon** [comment]
Oh. Do you happen to have any keyboard-specific tweaks?

**Comment by Hamzabdx** [comment]
Yes laetus/keyboardplus/shortmoji2/emojifontmanager btw keyboardplus and shortmoj 2 will cause respring loops unless turned off from choicy global and turned on in specific apps that i want them turned on in and they require xinam1ne from cypwn to work you dont have to try to figure it out its ok 👍

**Comment by sergealagon** [comment]
Thanks. I really appreciate your understanding. I just want everyone to have a working copy of my tweak without any issues. I'd still try to investigate, and even try to do a rewrite if possible. I'll leave this open for the meantime.

**Comment by Hamzabdx** [comment]
Btw installing backgrounder15 cc on its own without auto state from cypwn fixed this bug and now im sure bcz i tested it alot 
![image](https://github.com/user-attachments/assets/68ef4737-0140-4c8d-9e0f-49d3938c4c90)

**Comment by Hamzabdx** [comment]
Btw i posted this comment on your twitter “Great tweak can you add option that keeps a specific app alive even after closing it from app switcher also an option to have that app use the least amount of cpu gpu and ram possible thanks alot Can you also make it so it shows the indicators in app switcher too also can you add a control center switch where you can switch an app on or off from cc also switch the whole tweak on/off from the same cc button thanks in advance” id be willing to pay for a tweak like this basically a “bakgrunnr” clone you can make it and put it as paid in a different repo than havoc and cypwn wont crack it bcz they have a problem with havoc

**Comment by sergealagon** [comment]
That’s weird but an interesting discovery. Kinda weird since Immortalizer should work independently.

On bright side, I think I found the culprit. Will try to look into it further and fix this as soon as possible. 

As for feature request, I will try to work on it too. For now I’ll mainly focus on fixing bugs :) I want you guys to have a fully working tweak with no bugs :)

**Comment by Hamzabdx** [comment]
Thanks bro
